-- ============================================
-- Fix Tranche Coupon Recalculation Rules
-- Created: 2025-11-11
-- Purpose: Apply 30% flat tax ONLY for physical persons when tranche parameters change
-- ============================================

-- Function to recalculate coupons for all subscriptions in a tranche
CREATE OR REPLACE FUNCTION recalculate_tranche_coupons(p_tranche_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_taux_nominal numeric;
  v_projet_taux_nominal numeric;
  v_projet_id uuid;
  v_subscription RECORD;
  v_investor_type text;
  v_coupon_brut numeric;
  v_coupon_net numeric;
BEGIN
  -- Get tranche info (taux_nominal can be null if using project's)
  SELECT t.taux_nominal, t.projet_id, p.taux_nominal
  INTO v_taux_nominal, v_projet_id, v_projet_taux_nominal
  FROM tranches t
  JOIN projets p ON p.id = t.projet_id
  WHERE t.id = p_tranche_id;

  -- Use tranche taux_nominal if set, otherwise use project's
  v_taux_nominal := COALESCE(v_taux_nominal, v_projet_taux_nominal);

  -- If no taux_nominal available, exit
  IF v_taux_nominal IS NULL THEN
    RETURN;
  END IF;

  -- Loop through all subscriptions for this tranche
  FOR v_subscription IN
    SELECT s.id, s.montant_investi, s.investisseur_id
    FROM souscriptions s
    WHERE s.tranche_id = p_tranche_id
  LOOP
    -- Get investor type
    SELECT type INTO v_investor_type
    FROM investisseurs
    WHERE id = v_subscription.investisseur_id;

    -- Calculate coupon brut (annual coupon based on taux_nominal)
    v_coupon_brut := (v_subscription.montant_investi * v_taux_nominal) / 100;

    -- Calculate coupon net
    -- Physique: 30% flat tax -> net = brut * 0.7
    -- Morale: no flat tax -> net = brut
    IF v_investor_type = 'physique' THEN
      v_coupon_net := v_coupon_brut * 0.7;
    ELSE
      v_coupon_net := v_coupon_brut;
    END IF;

    -- Update subscription with recalculated coupons
    UPDATE souscriptions
    SET
      coupon_brut = v_coupon_brut,
      coupon_net = v_coupon_net
    WHERE id = v_subscription.id;

    -- Log the update for debugging
    RAISE NOTICE 'Updated subscription % - Type: %, Brut: %, Net: %',
      v_subscription.id, v_investor_type, v_coupon_brut, v_coupon_net;
  END LOOP;
END;
$$;

-- Function to recalculate coupons and schedules when tranche parameters change
CREATE OR REPLACE FUNCTION recalculate_on_tranche_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only recalculate if financial parameters changed
  IF (NEW.taux_nominal IS DISTINCT FROM OLD.taux_nominal) OR
     (NEW.periodicite_coupons IS DISTINCT FROM OLD.periodicite_coupons) OR
     (NEW.duree_mois IS DISTINCT FROM OLD.duree_mois) OR
     (NEW.date_emission IS DISTINCT FROM OLD.date_emission) THEN

    RAISE NOTICE 'Tranche % financial parameters changed - recalculating coupons', NEW.id;

    -- Recalculate all coupons for this tranche
    PERFORM recalculate_tranche_coupons(NEW.id);

    -- Delete old payment schedules (coupons_echeances)
    DELETE FROM coupons_echeances
    WHERE souscription_id IN (
      SELECT id FROM souscriptions WHERE tranche_id = NEW.id
    );

    RAISE NOTICE 'Deleted old payment schedules for tranche %', NEW.id;

    -- Note: Payment schedules need to be regenerated by calling generate_coupon_schedule
    -- This should be done by the application after the update
  END IF;

  RETURN NEW;
END;
$$;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS trigger_recalculate_on_tranche_update ON tranches;

-- Create trigger on tranches table
CREATE TRIGGER trigger_recalculate_on_tranche_update
  AFTER UPDATE ON tranches
  FOR EACH ROW
  EXECUTE FUNCTION recalculate_on_tranche_update();

-- Add comments
COMMENT ON FUNCTION recalculate_tranche_coupons IS 'Recalculates coupon_brut and coupon_net for all subscriptions in a tranche. Applies 30% flat tax ONLY for physical persons.';
COMMENT ON FUNCTION recalculate_on_tranche_update IS 'Trigger function that recalculates coupons when tranche financial parameters change';
COMMENT ON TRIGGER trigger_recalculate_on_tranche_update ON tranches IS 'Recalculates coupons and deletes old payment schedules when tranche parameters change';
