-- ============================================
-- Fix Project Update Trigger
-- Created: 2025-12-14
-- Purpose: Fix bugs in recalculate_on_project_update trigger
-- ============================================

-- Fix the trigger function to use correct column names and relationships
CREATE OR REPLACE FUNCTION recalculate_on_project_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only recalculate if financial parameters changed
  IF (NEW.taux_nominal IS DISTINCT FROM OLD.taux_nominal) OR
     (NEW.periodicite_coupons IS DISTINCT FROM OLD.periodicite_coupons) OR
     (NEW.duree_mois IS DISTINCT FROM OLD.duree_mois) THEN  -- ✅ Fixed: was maturite_mois

    RAISE NOTICE 'Project % financial parameters changed - recalculating coupons', NEW.id;

    -- Recalculate all coupons for all tranches in this project
    -- Note: This uses the recalculate_tranche_coupons function for each tranche
    PERFORM recalculate_tranche_coupons(t.id)
    FROM tranches t
    WHERE t.projet_id = NEW.id;

    -- Delete old payment schedules (coupons_echeances) for all tranches in this project
    -- Only delete pending ones, keep paid coupons
    DELETE FROM coupons_echeances
    WHERE souscription_id IN (
      SELECT s.id
      FROM souscriptions s
      JOIN tranches t ON s.tranche_id = t.id  -- ✅ Fixed: join through tranches
      WHERE t.projet_id = NEW.id
    )
    AND statut != 'payé';  -- ✅ Keep paid coupons

    RAISE NOTICE 'Deleted pending payment schedules for project %', NEW.id;

    -- Note: Payment schedules need to be regenerated by calling regenerate-echeancier Edge Function
    -- This should be done by the application after the update
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION recalculate_on_project_update IS 'Trigger function that recalculates coupons when project financial parameters change (FIXED: uses duree_mois and joins through tranches)';
